#define S_MICROSCOPIC       (1 << 0)
#define S_MINISCULE         (1 << 1)
#define S_TINY              (1 << 2)
#define S_VERY_SMALL        (1 << 3)
#define S_SMALL             (1 << 4)
#define S_SOMEWHAT_SMALL    (1 << 5)
#define S_HUMAN_SIZED       (1 << 6)
#define S_SOMEWHAT_LARGE    (1 << 7)
#define S_LARGE             (1 << 8)
#define S_HUGE              (1 << 9)
#define S_GIGANTIC          (1 << 10)
#define S_VAST              (1 << 11)
#define S_MAX_SIZE_BIT      S_VAST
