string old_convert_ascii(int i){
    string ret;

    switch(i){
    case 33: ret = "!"; break;
    case 34: ret = "\""; break;
    case 35: ret = "#"; break;
    case 36: ret = "$"; break;
    case 37: ret = "%"; break;
    case 38: ret = "&"; break;
    case 39: ret = "'"; break;
    case 40: ret = "("; break;
    case 41: ret = ")"; break;
    case 42: ret = "*"; break;
    case 43: ret = "+"; break;
    case 44: ret = ","; break;
    case 45: ret = "-"; break;
    case 46: ret = "."; break;
    case 47: ret = "/"; break;
    case 48: ret = "0"; break;
    case 49: ret = "1"; break;
    case 50: ret = "2"; break;
    case 51: ret = "3"; break;
    case 52: ret = "4"; break;
    case 53: ret = "5"; break;
    case 54: ret = "6"; break;
    case 55: ret = "7"; break;
    case 56: ret = "8"; break;
    case 57: ret = "9"; break;
    case 58: ret = ":"; break;
    case 59: ret = "\059"; break;
    case 60: ret = "<"; break;
    case 61: ret = "="; break;
    case 62: ret = ">"; break;
    case 63: ret = "?"; break;
    case 64: ret = "@"; break;
    case 65: ret = "A"; break;
    case 66: ret = "B"; break;
    case 67: ret = "C"; break;
    case 68: ret = "D"; break;
    case 69: ret = "E"; break;
    case 70: ret = "F"; break;
    case 71: ret = "G"; break;
    case 72: ret = "H"; break;
    case 73: ret = "I"; break;
    case 74: ret = "J"; break;
    case 75: ret = "K"; break;
    case 76: ret = "L"; break;
    case 77: ret = "M"; break;
    case 78: ret = "N"; break;
    case 79: ret = "O"; break;
    case 80: ret = "P"; break;
    case 81: ret = "Q"; break;
    case 82: ret = "R"; break;
    case 83: ret = "S"; break;
    case 84: ret = "T"; break;
    case 85: ret = "U"; break;
    case 86: ret = "V"; break;
    case 87: ret = "W"; break;
    case 88: ret = "X"; break;
    case 89: ret = "Y"; break;
    case 90: ret = "Z"; break;
    case 91: ret = "["; break;
    case 92: ret = "\\"; break;
    case 93: ret = "]"; break;
    case 94: ret = "^"; break;
    case 95: ret = "_"; break;
    case 96: ret = "`"; break;
    case 97: ret = "a"; break;
    case 98: ret = "b"; break;
    case 99: ret = "c"; break;
    case 100: ret = "d"; break;
    case 101: ret = "e"; break;
    case 102: ret = "f"; break;
    case 103: ret = "g"; break;
    case 104: ret = "h"; break;
    case 105: ret = "i"; break;
    case 106: ret = "j"; break;
    case 107: ret = "k"; break;
    case 108: ret = "l"; break;
    case 109: ret = "m"; break;
    case 110: ret = "n"; break;
    case 111: ret = "o"; break;
    case 112: ret = "p"; break;
    case 113: ret = "q"; break;
    case 114: ret = "r"; break;
    case 115: ret = "s"; break;
    case 116: ret = "t"; break;
    case 117: ret = "u"; break;
    case 118: ret = "v"; break;
    case 119: ret = "w"; break;
    case 120: ret = "x"; break;
    case 121: ret = "y"; break;
    case 122: ret = "z"; break;
    case 123: ret = "{"; break;
    case 124: ret = ""; break;
    case 124: ret = ""; break;
    case 125: ret = "}"; break;
    case 126: ret = "~"; break;
    case 127: ret = ""; break;
    case 128: ret = "¿"; break;
    case 129: ret = "¿"; break;
    case 130: ret = "¿"; break;
    case 131: ret = "¿"; break;
    case 132: ret = "¿"; break;
    case 133: ret = "¿"; break;
    case 134: ret = "¿"; break;
    case 135: ret = "¿"; break;
    case 136: ret = "¿"; break;
    case 137: ret = "¿"; break;
    case 138: ret = "¿"; break;
    case 139: ret = "¿"; break;
    case 140: ret = "¿"; break;
    case 141: ret = "¿"; break;
    case 142: ret = "¿"; break;
    case 143: ret = "¿"; break;
    case 143: ret = "¿"; break;
    case 144: ret = "¿"; break;
    case 145: ret = "'"; break;
    case 146: ret = "'"; break;
    case 147: ret = "¿"; break;
    case 148: ret = "¿"; break;
    case 149: ret = "¿"; break;
    case 150: ret = "¿"; break;
    case 151: ret = "¿"; break;
    case 152: ret = "¿"; break;
    case 153: ret = "¿"; break;
    case 154: ret = "¿"; break;
    case 155: ret = "¿"; break;
    case 156: ret = "¿"; break;
    case 157: ret = "¿"; break;
    case 158: ret = "¿"; break;
    case 159: ret = "¿"; break;
    case 160: ret = "\160"; break;
    case 161: ret = "¡"; break;
    case 162: ret = "¢"; break;
    case 163: ret = "£"; break;
    case 164: ret = "¤"; break;
    case 165: ret = "¥"; break;
    case 166: ret = "¦"; break;
    case 167: ret = "§"; break;
    case 168: ret = "¨"; break;
    case 169: ret = "©"; break;
    case 170: ret = "ª"; break;
    case 171: ret = "«"; break;
    case 172: ret = "¬"; break;
    case 173: ret = "­"; break;
    case 174: ret = "®"; break;
    case 175: ret = "¯"; break;
    case 176: ret = "°"; break;
    case 177: ret = "±"; break;
    case 178: ret = "²"; break;
    case 179: ret = "³"; break;
    case 180: ret = "´"; break;
    case 181: ret = "µ"; break;
    case 182: ret = "¶"; break;
    case 183: ret = "·"; break;
    case 184: ret = "¸"; break;
    case 185: ret = "¹"; break;
    case 186: ret = "º"; break;
    case 187: ret = "»"; break;
    case 188: ret = "¼"; break;
    case 189: ret = "½"; break;
    case 190: ret = "¾"; break;
    case 191: ret = "¿"; break;
    case 192: ret = "À"; break;
    case 193: ret = "Á"; break;
    case 194: ret = "Â"; break;
    case 195: ret = "Ã"; break;
    case 196: ret = "Ä"; break;
    case 197: ret = "Å"; break;
    case 198: ret = "Æ"; break;
    case 199: ret = "Ç"; break;
    case 200: ret = "È"; break;
    case 201: ret = "É"; break;
    case 202: ret = "Ê"; break;
    case 203: ret = "Ë"; break;
    case 204: ret = "Ì"; break;
    case 205: ret = "Í"; break;
    case 206: ret = "Î"; break;
    case 207: ret = "Ï"; break;
    case 208: ret = "Ğ"; break;
    case 209: ret = "Ñ"; break;
    case 210: ret = "Ò"; break;
    case 211: ret = "Ó"; break;
    case 212: ret = "Ô"; break;
    case 213: ret = "Õ"; break;
    case 214: ret = "Ö"; break;
    case 215: ret = "×"; break;
    case 216: ret = "Ø"; break;
    case 217: ret = "Ù"; break;
    case 218: ret = "Ú"; break;
    case 219: ret = "Û"; break;
    case 220: ret = "Ü"; break;
    case 221: ret = "İ"; break;
    case 222: ret = "Ş"; break;
    }

    if(!ret) switch(i){
    case 223: ret = "ß"; break;
    case 224: ret = "à"; break;
    case 225: ret = "á"; break;
    case 226: ret = "â"; break;
    case 227: ret = "ã"; break;
    case 228: ret = "ä"; break;
    case 229: ret = "å"; break;
    case 230: ret = "æ"; break;
    case 231: ret = "ç"; break;
    case 232: ret = "è"; break;
    case 233: ret = "é"; break;
    case 234: ret = "ê"; break;
    case 235: ret = "ë"; break;
    case 236: ret = "ì"; break;
    case 237: ret = "í"; break;
    case 238: ret = "î"; break;
    case 239: ret = "ï"; break;
    case 240: ret = "ğ"; break;
    case 241: ret = "ñ"; break;
    case 242: ret = "ò"; break;
    case 243: ret = "ó"; break;
    case 244: ret = "ô"; break;
    case 245: ret = "õ"; break;
    case 246: ret = "ö"; break;
    case 247: ret = "÷"; break;
    case 248: ret = "ø"; break;
    case 249: ret = "ù"; break;
    case 250: ret = "ú"; break;
    case 251: ret = "û"; break;
    case 252: ret = "ü"; break;
    case 253: ret = "ı"; break;
    case 254: ret = "ş"; break;
    default: ret = "";
    }
    return ret;
}

string convert_ascii(int i){
    return sprintf("%c",i);
}

mixed convert_into_ascii(string str){
    int i;
    string *tmparr = ({});
    int *intarr = ({});
    if(!str) return 0;
    tmparr = explode(str,"");
    foreach(string element in tmparr){
	for(i=0;i<256;i++){
	    if(sprintf("%c",i) == element) intarr += ({ i });
	}
    }
    return intarr;
}






