#!/bin/bash
rm /tmp/thingy.txt
for i in `find .|grep "\.c"|grep -v "\.cfg"|grep -v "\.css"`
do
if cat $i | grep "@EndText" 
then
echo "Skipping $i"
echo $i >> /tmp/thingy.txt
else
echo "Indenting "$i
vim -c "set tabstop=4 shiftwidth=4 expandtab retab" -esc "normal gg=G" -c "wq" $i
fi
done

