#ifndef s_events_h
#define s_events_h

#include <dirs.h>

#define LIB_ACTIVATE     DIR_EVENTS "/activate"
#define LIB_AIM          DIR_EVENTS "/aim"
#define LIB_APPLY        DIR_EVENTS "/apply"
#define LIB_BAIT         DIR_EVENTS "/bait"
#define LIB_BAIT_WITH    DIR_EVENTS "/bait_with"
#define LIB_BURY         DIR_EVENTS "/bury"
#define LIB_BUY          DIR_EVENTS "/buy"
#define LIB_CLIMB        DIR_EVENTS "/climb"
#define LIB_CLOSE        DIR_EVENTS "/close"
#define LIB_CONSULT      DIR_EVENTS "/consult"
#define LIB_DESCRIBE     DIR_EVENTS "/describe"
#define LIB_DIG          DIR_EVENTS "/dig"
#define LIB_DIG_WITH     DIR_EVENTS "/dig_with"
#define LIB_DISARM       DIR_EVENTS "/disarm"
#define LIB_DRINK        DIR_EVENTS "/drink"
#define LIB_DROP         DIR_EVENTS "/drop"
#define LIB_FALL         DIR_EVENTS "/fall"
#define LIB_FLOAT        DIR_EVENTS "/float"
#define LIB_GET          DIR_EVENTS "/get"
#define LIB_GET_FROM     DIR_EVENTS "/get_from"
#define LIB_GIVE         DIR_EVENTS "/give"
#define LIB_JUMP         DIR_EVENTS "/jump"
#define LIB_INSTALL      DIR_EVENTS "/install"
#define LIB_LISTEN       DIR_EVENTS "/listen"
#define LIB_KNEEL        DIR_EVENTS "/kneel"
#define LIB_KNOCK        DIR_EVENTS "/knock"
#define LIB_LOAD         DIR_EVENTS "/load"
#define LIB_LOCK         DIR_EVENTS "/lock"
#define LIB_LOCK_WITH    DIR_EVENTS "/lock_with"
#define LIB_LOOK         DIR_EVENTS "/look"
#define LIB_LOOK_IN      DIR_EVENTS "/look_in"
#define LIB_POISON       DIR_EVENTS "/poison"
#define LIB_PRESS        DIR_EVENTS "/press"
#define LIB_PULL         DIR_EVENTS "/pull"
#define LIB_PUT          DIR_EVENTS "/put"
#define LIB_READ         DIR_EVENTS "/read"
#define LIB_ROCK         DIR_EVENTS "/rock"
#define LIB_ROLL         DIR_EVENTS "/roll"
#define LIB_SCRATCH      DIR_EVENTS "/scratch"
#define LIB_SEARCH       DIR_EVENTS "/search"
#define LIB_SHAKE        DIR_EVENTS "/shake"
#define LIB_SHOW         DIR_EVENTS "/show"
#define LIB_SIT          DIR_EVENTS "/sit"
#define LIB_SINK         DIR_EVENTS "/sink"
#define LIB_SELL         DIR_EVENTS "/sell"
#define LIB_SMELL        DIR_EVENTS "/smell"
#define LIB_SMOKE        DIR_EVENTS "/smoke"
#define LIB_STOP         DIR_EVENTS "/stop"
#define LIB_SWIM         DIR_EVENTS "/swim"
#define LIB_SWIVEL       DIR_EVENTS "/swivel"
#define LIB_TOUCH        DIR_EVENTS "/touch"
#define LIB_WEAR         DIR_EVENTS "/wear"
#define LIB_WIELD        DIR_EVENTS "/wield"
#define LIB_SHOOT        DIR_EVENTS "/shoot"
#define LIB_TURN         DIR_EVENTS "/turn"
#define LIB_MANIPULATE   DIR_EVENTS "/manipulate"
#define LIB_CRAWL        DIR_EVENTS "/crawl"
#define LIB_LIE          DIR_EVENTS "/lie"
#define LIB_FLY          DIR_EVENTS "/fly"

#endif /* s_events_h */
