#ifndef s_save_h
#define s_save_h

#include <dirs.h>

#define SAVE_BANISH        DIR_SAVE "/banish"
#define SAVE_BOOKS         DIR_SAVE "/books"
#define SAVE_BUGS          DIR_SAVE "/bugs"
#define SAVE_CHARACTER     DIR_SECURE_SAVE "/character"
#define SAVE_CLASSES       DIR_SAVE "/classes"
#define SAVE_CLASS         DIR_SAVE "/class"
#define SAVE_CONFIG        DIR_SAVE "/config"
#define SAVE_DEVIATION     DIR_SAVE "/deviation"
#define SAVE_ECONOMY       DIR_SAVE "/economy"
#define SAVE_ESTATES       DIR_SAVE "/estates"
#define SAVE_EVENTS        DIR_SAVE "/events"
#define SAVE_FILES         DIR_SECURE_SAVE "/files"
#define SAVE_FUNCTIONS     DIR_SECURE_SAVE "/functions"
#define SAVE_GOSSIP        DIR_GOSSIP "/gossip"
#define SAVE_ICP           DIR_SECURE_SAVE "/icp"
#define SAVE_INET          DIR_SECURE_SAVE "/inet"
#define SAVE_INTERMUD      DIR_SAVE "/intermud"
#define SAVE_INSTANCES     DIR_SECURE_SAVE "/instances"
#define SAVE_IMC2          DIR_SECURE_SAVE "/imc2"
#define SAVE_IMC2_SERVER   DIR_SECURE_SAVE "/imc2_server"
#define SAVE_LIVEUPGRADE   DIR_SECURE_SAVE "/liveupgrade"
#define SAVE_MAILQUEUE     DIR_DATA "/mailqueue"
#define SAVE_MASTER        DIR_SECURE_SAVE "/master"
#define SAVE_MAP           DIR_SAVE "/map"
#define SAVE_MEETINGS      DIR_SAVE "/meetings"
#define SAVE_MUDINFO       DIR_SECURE_SAVE "/mudinfo"
#define SAVE_NAMESERVER    DIR_SAVE "/network"
#define SAVE_NOTIFY        DIR_SAVE "/notify"
#define SAVE_QUESTS        DIR_SECURE_SAVE "/quests"
#define SAVE_PARTIES       DIR_SAVE "/parties"
#define SAVE_PLAYER_LIST   DIR_SECURE_SAVE "/player_list"
#define SAVE_POLITICS      DIR_SECURE_SAVE "/politics"
#define SAVE_PORTAL        DIR_SAVE "/portal"
#define SAVE_RACES         DIR_SAVE "/races"
#define SAVE_RELOAD        DIR_SECURE_SAVE "/reload"
#define SAVE_ROOMS         DIR_SAVE "/rooms"
#define SAVE_ROUTER        DIR_SECURE_SAVE "/router"
#define SAVE_SKILLS        DIR_SAVE "/skills"
#define SAVE_SERVICES      DIR_SAVE "/services"
#define SAVE_SESSIONS      DIR_SECURE_SAVE "/sessions"
#define SAVE_SNOOP         DIR_SECURE_SAVE "/snoop"
#define SAVE_SOUL          DIR_SAVE "/soul"
#define SAVE_STARGATE      DIR_SAVE "/stargate"
#define SAVE_STATS         DIR_SAVE "/stats"
#define SAVE_STATISTICS    DIR_SAVE "/statistics"
#define SAVE_TYPES         DIR_SAVE "/types"
#define SAVE_UNIQUE        DIR_SAVE "/unique"
#define SAVE_WEIRDER       DIR_SECURE_SAVE "/weirder"

#endif /* s_save_h */
